// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdvnqhCEvBx0xARmhGYJYr-JseP5CZMUE',
    appId: '1:240290760447:web:d03c3e0e220b996ade6eca',
    messagingSenderId: '240290760447',
    projectId: 'fir-t1-ba69b',
    authDomain: 'fir-t1-ba69b.firebaseapp.com',
    storageBucket: 'fir-t1-ba69b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtIgHvvI8TNM0cLEIEppO3lloD1u80abo',
    appId: '1:240290760447:android:ab9601a3fca47784de6eca',
    messagingSenderId: '240290760447',
    projectId: 'fir-t1-ba69b',
    storageBucket: 'fir-t1-ba69b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVRD1bhTWjkxBcRmEJm3Y5lLAkQN1-EnY',
    appId: '1:240290760447:ios:5a9f824b9052f7f4de6eca',
    messagingSenderId: '240290760447',
    projectId: 'fir-t1-ba69b',
    storageBucket: 'fir-t1-ba69b.firebasestorage.app',
    iosBundleId: 'com.example.letscountPm1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVRD1bhTWjkxBcRmEJm3Y5lLAkQN1-EnY',
    appId: '1:240290760447:ios:5a9f824b9052f7f4de6eca',
    messagingSenderId: '240290760447',
    projectId: 'fir-t1-ba69b',
    storageBucket: 'fir-t1-ba69b.firebasestorage.app',
    iosBundleId: 'com.example.letscountPm1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdvnqhCEvBx0xARmhGYJYr-JseP5CZMUE',
    appId: '1:240290760447:web:e67d01a86fb4bc90de6eca',
    messagingSenderId: '240290760447',
    projectId: 'fir-t1-ba69b',
    authDomain: 'fir-t1-ba69b.firebaseapp.com',
    storageBucket: 'fir-t1-ba69b.firebasestorage.app',
  );
}
